#!/usr/bin/env python2

import sys
import re

if len(sys.argv) != 4:
    sys.exit("Three arguments: start line pattern, end line pattern and file expected")

start_line_pattern = sys.argv[1]
end_line_pattern = sys.argv[2]
file_name = sys.argv[3]

in_section = False

with open(file_name, 'rt') as file:
    for line in file:
        if re.match(start_line_pattern, line):
            in_section = True
        elif re.match(end_line_pattern, line):
            if in_section:
                in_section = False
                print line
                print "----"

        if in_section:
            print line
