#!/usr/bin/env python3

# git pre-commit hook forbiding certain phrases
# need gitpython to work:
# pip3 install gitpython

BANNED_PHRASES = [
	'radek',
	'??',
	'System.out.print'
]

import git
import itertools
import sys

found_banned_phrases = []

def check_banned_phrases(diff):
	patch = diff.diff.decode('UTF-8')
	for banned_phrase in BANNED_PHRASES:
		for line in patch.split('\n'):
			if line.startswith('+') and banned_phrase in line:
				plus_striped = line[1:]
				found_banned_phrases.append((diff.b_path, plus_striped))

repo = git.Repo('.')
diff = repo.head.commit.diff(create_patch = True)

for d in itertools.chain(diff.iter_change_type('M'), diff.iter_change_type('A')):
	check_banned_phrases(d)

if found_banned_phrases:
	print('Banned phrases found:')
	print('\n'.join(map(lambda e: ':'.join(e), found_banned_phrases)))
	sys.exit(1)

